<?php
// Global Scope
$globalVar = 10;

function globalExample() {
    echo "Global variable inside function: " . $GLOBALS['globalVar'] . "<br>";
}

globalExample(); // Output: Global variable inside function: 10

// Function Scope
function functionScope() {
    $localVar = 5; // Only accessible within this function
    echo "Local variable inside function: " . $localVar . "<br>";
}

functionScope(); // Output: Local variable inside function: 5

// Block Scope (PHP 7.0+)
if (true) {
    $blockVar = "Hello"; // Only accessible within this block
    echo "Block variable: " . $blockVar . "<br>";
}

// Class Scope
class MyClass {
    public $classVar = 42; // Accessible within class

    public function printVar() {
        echo "Class variable: " . $this->classVar . "<br>";
    }
}

$obj = new MyClass();
$obj->printVar(); // Output: Class variable: 42<br>

// Static Variable Scope
function counter() {
    static $count = 0; // Persists between function calls
    $count++;
    echo "Counter: " . $count . "<br>";
}

counter(); // Output: Counter: 1
counter(); // Output: Counter: 2

// Super Global Scope
$name = $_GET['name']; // Accessing superglobal variable
echo "Value from query parameter 'name': " . $name;
?>

<!-- 
$GLOBALS: An associative array containing all global variables.
$_SERVER: Provides information about server and execution environment.
$_REQUEST: Combines $_GET, $_POST, and $_COOKIE data.
$_POST: Contains data sent to the script via HTTP POST method.
$_GET: Contains data sent to the script via URL query parameters (GET method).
$_FILES: Contains information about uploaded files via HTTP POST.
$_ENV: Provides access to environment variables.
$_COOKIE: Contains data sent by the client's browser as cookies.
$_SESSION: Provides access to session variables.
$php_errormsg: Contains the last error message generated by PHP.
$HTTP_RAW_POST_DATA: Contains raw POST data.
$http_response_header: Contains the headers of the last HTTP response.
-->

//static keyword
<?php
function incrementCounter() {
    static $count = 0;
    $count++;
    echo "Count: " . $count . "<br>";
}
incrementCounter(); // Output: Count: 1
incrementCounter(); // Output: Count: 2
class MyClass {
    public static $staticVar = 0;

    public static function incrementStaticVar() {
        self::$staticVar++;
    }
}
MyClass::incrementStaticVar();
echo MyClass::$staticVar . "<br>"; // Output: 1

//global keyword
$globalVar = 10;
function modifyGlobal() {
    global $globalVar;
    $globalVar = 20;
}
modifyGlobal();
echo $globalVar; // Output: 20
?> 
